### ISSUE TITLE
[pycparser] unicode characters are unsupported outside of quoted strings

### ISSUE THREAD

**Issue by Ruenzuo** [samdmarshall/pyconfig#4]
Great tool, thanks a lot for open sourcing it 🎉

I have one question, currently I'm playing around with it and I notice (following the examples provided) that if I use a string value in the DSL, like:

```
include "Pods/Target Support Files/Pods-XING/Pods-XING.debug.xcconfig"

setting PRODUCT_NAME {
    for XING {
        "XING α"
    }
}
```

The output will be the following:

```
// Generated by pyconfig
#include "Pods/Target Support Files/Pods-XING/Pods-XING.debug.xcconfig"
PRODUCT_NAME_XING = "XING α"
PRODUCT_NAME = $(PRODUCT_NAME_$(CONFIGURATION))
```

Which will cause something like this (if I use `$(PRODUCT_NAME_XING)` in the `Product Name` configuration in my Xcode project):

![screen shot 2016-06-03 at 15 01 47](https://cloud.githubusercontent.com/assets/346590/15779363/1e9ff602-299c-11e6-82d4-65114f8448d9.png)

Ideally I would like to get rid of the quotation marks in there. How could I achieve this? I already tried to use `XING α` instead of `"XING α"` in there, but that's not valid Python so the DSL doesn't work I think.

**Comment by samdmarshall** [comment]
I'm pretty sure that if you remove the `"`s from the define so it that it appears as:

```
include "Pods/Target Support Files/Pods-XING/Pods-XING.debug.xcconfig"

setting PRODUCT_NAME {
    for XING {
        XING α
    }
}
```

That should work. If not then that is definitely a bug. I believe I had designed it to preserve quotes as they were input into the pyconfig file.

**Comment by samdmarshall** [comment]
OK, having not seen your edit, I deleted my previous reply to this saying to remove the quotation marks. The DSL isn't python based, the tool happens to be written in python. If that doesn't work then if you could please submit a sample project that I could work with to see about fixing this. Thanks.

**Comment by Ruenzuo** [comment]
Here's a sample project where you can reproduce it: https://github.com/Ruenzuo/pyconfig-sample

Running this rake task should set up the project property (after pod install...): https://github.com/Ruenzuo/pyconfig-sample/blob/master/Rakefile#L26-L30

By the way, without the quotation marks I get the following output:

```
nb-rcrisostomo:deploy-tasks renzo.crisostomo$ bundle exec rake bootstrap['Alpha']
Traceback (most recent call last):
  File "/usr/local/Cellar/pyconfig/HEAD/libexec/bin/pyconfig", line 9, in <module>
    load_entry_point('pyconfig==1.0', 'console_scripts', 'pyconfig')()
  File "/usr/local/Cellar/pyconfig/HEAD/libexec/lib/python2.7/site-packages/pyconfig/main.py", line 78, in main
    parsed_contents = interpreter.parse(args.lint, pyconfig_contents)
  File "/usr/local/Cellar/pyconfig/HEAD/libexec/lib/python2.7/site-packages/pyconfig/interpreter.py", line 41, in parse
    results = pyc._config.parseString(pyconfig_contents)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pyparsing.py", line 1041, in parseString
    raise exc
pyparsing.ParseException: Expected "}" (at char 110), (line:4, col:14)
```

**Comment by samdmarshall** [comment]
OK, it looks like a problem with the parser not liking the `α` character, because it accepts the string `XING a` without quotes and generates the following:

```
// Generated by pyconfig
#include "Pods/Target Support Files/Pods-XING/Pods-XING.release.xcconfig"
PRODUCT_NAME_XING = XING a
PRODUCT_NAME = $(PRODUCT_NAME_$(CONFIGURATION))
```

This means I will have to update the script to not use the built-in tool for parsing comma separate lists. This means I could address a few other issues, such as not being able to put comments inside of the `if` or `for` statements. I am going to try to look at this over the weekend.


Also as a note, the DSL isn't a python derivative, i've been calling the files `pyconfig` after the name of the tool which follows a common convention (at least my understanding of it) that prefixes things with `py` when they are written in python.

**Comment by samdmarshall** [comment]
OK I think I've pin-pointed the problem. The method I am using to parse the values is `commaSeparatedList` which is defined as such:

```
commaSeparatedList = delimitedList( Optional( quotedString.copy() | _commasepitem, default="") ).setName("commaSeparatedList")
```
Which is saying a delimited list of zero or more values that are either a copy of `quotedString()` or a `_commasepitem`. The code works with the quotes because it copies the string literally instead of trying to parse it. If there is no quotes around the item then it will use `_commasepitem` which is defined as:

```
_commasepitem = Combine(OneOrMore(Word(printables, excludeChars=',') + 
                                  Optional( Word(" \t") + 
                                            ~Literal(",") + ~LineEnd() ) ) ).streamline().setName("commaItem") 
```
This defines the word that is being parsed as only containing the definition of `printables` which is:

```
printables = "".join(c for c in string.printable if c not in string.whitespace) 
```
And using the Python repl this is defined as:

```
Samantha@Pegasus:~ $ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import string
>>> print("".join(c for c in string.printable if c not in string.whitespace))
0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
>>> 
```
As you can see this doesn't contain the `α` character, so pyparsing reads this as an invalid word and thus you get that error. As I mentioned in the previous comment, I will have to look at finding a way to properly handle this case. This most likely means rewriting the `commaSeparatedList` construct. Since this is a pretty core part I will have to do this pretty carefully.

**Comment by Ruenzuo** [comment]
Whoa, thanks for looking into this and for the great detail explanation! Feeling a little dumb for not trying it out without the `α` character before opening this :blush:

**Comment by samdmarshall** [comment]
Well I'd consider this a valid bug regardless as xcconfigs support using that character in the `PRODUCT_NAME`. I am going to evaluate my options, and my current suggestion is that you use only characters in `pyparsing.printables` for strings that don't have quotes.

**Comment by samdmarshall** [comment]
This should be fixed on `master` now. I tried it out with your example and it was able to generate the settings file correctly, could you verify as well before i close this?

**Comment by Ruenzuo** [comment]
Yes, it works 🎉
